### PR TITLE
Fix #35 to follow up the API's response changes

### LINKED ISSUE #35: [ Report ] Can't create a TOC because GitHub API's response has changed
Not a bug of `gh-md-toc`, but currently **it can't create a TOC because the GitHub API response has changed**.

It is not clear when this started. It appears that the anchor tag now contains the "`aria-hidden`" attribute.

```diff
- <h1><a id="user-content-one" class="anchor" href="#one"><span class="octicon octicon-link"></span></a>One</h1>
+ <h1><a id="user-content-one" class="anchor" aria-hidden="true" href="#one"><span aria-hidden="true" class="octicon octicon-link"></span></a>One</h1>
```

**To Reproduce**

```shellsession
$ # Markdown to be ToC
$ cat sample.md
# One

Uno

## Two

Dos

### Three

Tres

```

```shellsession
$ # Print ToC
$ gh-md-toc ./sample.md

Table of Contents
=================


Created by [gh-md-toc](https://github.com/ekalinin/github-markdown-toc.go)
```

**Expected behavior**

```shellsession
$ # Print ToC
$ gh-md-toc ./sample.md

Table of Contents
=================

* [One](./sample.md#one)
  * [Two](./sample.md#two)
    * [Three](./sample.md#three)

Created by [gh-md-toc](https://github.com/ekalinin/github-markdown-toc.go)
```

**Environment:**
 - OS: macOS Catalina (OSX 10.15.7)
   - `gh-md-toc` Version: 1.2.0 (via homebrew and `go install`)
 - OS: Alpine (Docker, `golang:alpine`)
   - `gh-md-toc` Version: 1.2.0 (via go install)

**Additional context**

```shellsession
$ gh-md-toc --debug ./sample.md

Table of Contents
=================

2022/08/24 13:54:59 Convert2HTML: start.
2022/08/24 13:54:59 IsRemoteFile: false
2022/08/24 13:54:59 Convert2HTML: local file: ./sample.md
2022/08/24 13:55:00 Convert2HTML: converted to html, size: 487
2022/08/24 13:55:00 Convert2HTML: write html file: ./sample.md.debug.html
2022/08/24 13:55:00 Convert2HTML: done.
2022/08/24 13:55:00 GrabToc: start, html size: 487
2022/08/24 13:55:00 GrabToc: matching ...
2022/08/24 13:55:00 GrabToc: processing groups ...
2022/08/24 13:55:00 Including starting from level 0
2022/08/24 13:55:00 GrabToc: done.

Created by [gh-md-toc](https://github.com/ekalinin/github-markdown-toc.go)
```
```shellsession
$ cat sample.md.debug.html
<h1><a id="user-content-one" class="anchor" aria-hidden="true" href="#one"><span aria-hidden="true" class="octicon octicon-link"></span></a>One</h1>
<p>Uno</p>
<h2><a id="user-content-two" class="anchor" aria-hidden="true" href="#two"><span aria-hidden="true" class="octicon octicon-link"></span></a>Two</h2>
<p>Dos</p>
<h3><a id="user-content-three" class="anchor" aria-hidden="true" href="#three"><span aria-hidden="true" class="octicon octicon-link"></span></a>Three</h3>
<p>Tres</p>
```

If changes to the API response are permanent, it may be necessary to modify the regular expression.

https://github.com/ekalinin/github-markdown-toc.go/blob/92ed8d078800c27609188d2f3bab4ab3a94ad8f6/ghdoc.go#L145-L148

### PR DESCRIPTION
**Pull request by KEINOS**
Even though it is a "cat-and-mouse" game with the GitHub API but here's the quick fix of the issue #35.

### CODE REVIEW

**Comment by KEINOS** [comment]
@ekalinin

Should I replace `io/ioutil` to `io` ?

Even though `make test` passes on Go v1.17 and v1.18, **on Go v1.19 I get the following error**.
`golangci-lint`(v1.49.0) wants us to use `io` and `os` package instead of `io/ioutil`.

```shellsession
$ make test
cmd/gh-md-toc/main.go:5:2: SA1019: "io/ioutil" has been deprecated since Go 1.16: As of Go 1.16, the same functionality is now provided by package io or package os, and those implementations should be preferred in new code. See the specific function documentation for details. (staticcheck)
	"io/ioutil"
	^
ghdoc.go:6:2: SA1019: "io/ioutil" has been deprecated since Go 1.16: As of Go 1.16, the same functionality is now provided by package io or package os, and those implementations should be preferred in new code. See the specific function documentation for details. (staticcheck)
	"io/ioutil"
	^
internals.go:7:2: SA1019: "io/ioutil" has been deprecated since Go 1.16: As of Go 1.16, the same functionality is now provided by package io or package os, and those implementations should be preferred in new code. See the specific function documentation for details. (staticcheck)
	"io/ioutil"
	^
make: *** [Makefile:14: lint] Error 1
```

**Comment by ekalinin** [comment]
> Should I replace io/ioutil to io ?

Yes, let's replace. Thanks!

**Comment by KEINOS** [comment]
@ekalinin

Done! Please run the CI when you have time. Hope it passes 🤞

**Comment by KEINOS** [comment]
@ekalinin

Additional tests have been added to cover the changes. Please re-run the CIs.
It should bring back the coverage to 88% 🤞

**Comment by ekalinin** [comment]
Thanks a lot!

**Pull request merged**
